# Uncomment and fill in whichever platforms apply.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [ease-my-work]
# ko_fi:
# buy_me_a_coffee:
# custom: []
